title: vERA NUARI
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://vera.github.io

aux_links:
  Template Repository: https://github.com/veranuari/just-the-docs-template
